I will code with the same order of the task instructions !!!

In [24]:
import numpy as np

In [25]:
grades = np.array(
    [[85, 78, 92, 88], [70, 76, 80, 65], [90, 88, 94, 91], [60, 65, 58, 62], [100, 95, 98, 97]]
    )

In [26]:
print(grades.shape) 


(5, 4)


In [27]:

st1_mean = np.mean(grades[0,:])
print(f"the mean of the first student is = {st1_mean}")
st2_mean = np.mean(grades[1,:])
print(f"the mean of the second student is = {st2_mean}")
st3_mean = np.mean(grades[2,:])
print(f"the mean of the third student is = {st3_mean}")
st4_mean = np.mean(grades[3,:])
print(f"the mean of the fourth student is = {st4_mean}")
st5_mean = np.mean(grades[4,:])
print(f"the mean of the fifth student is = {st5_mean}")

#? i thought of this procedure at first and then found out the next one after researching !!

means = np.mean(grades , axis=1)
means

the mean of the first student is = 85.75
the mean of the second student is = 72.75
the mean of the third student is = 90.75
the mean of the fourth student is = 61.25
the mean of the fifth student is = 97.5


array([85.75, 72.75, 90.75, 61.25, 97.5 ])

In [28]:
sub1_mean = np.mean(grades[:,0])
print(f"the mean of the first subject is = {sub1_mean}")
sub2_mean = np.mean(grades[:,1])
print(f"the mean of the first subject is = {sub2_mean}")
sub3_mean = np.mean(grades[:,2])
print(f"the mean of the first subject is = {sub3_mean}")
sub4_mean = np.mean(grades[:,3])
print(f"the mean of the first subject is = {sub4_mean}")

#? same idea here !! 
#? i kept them anyway

sub_means = np.mean(grades, axis=0)
sub_means


the mean of the first subject is = 81.0
the mean of the first subject is = 80.4
the mean of the first subject is = 84.4
the mean of the first subject is = 80.6


array([81. , 80.4, 84.4, 80.6])

In [29]:
means[means > 85] #! this the average greater than 85 !!

array([85.75, 90.75, 97.5 ])

In [30]:
grades_with_bonus = grades + 5 
grades_with_bonus

array([[ 90,  83,  97,  93],
       [ 75,  81,  85,  70],
       [ 95,  93,  99,  96],
       [ 65,  70,  63,  67],
       [105, 100, 103, 102]])

In [31]:
def min_max(arr):
    max = np.max(arr)
    min = np.min(arr)
    if max ==min:
        return np.zeros_like(arr) # this line i havent done in the task_0 but done here anyways , i searched for it and noticed it then wrote !!!
    
    norm= (arr - min) / (max - min)

    return norm

min_max(grades)
    

array([[0.64285714, 0.47619048, 0.80952381, 0.71428571],
       [0.28571429, 0.42857143, 0.52380952, 0.16666667],
       [0.76190476, 0.71428571, 0.85714286, 0.78571429],
       [0.04761905, 0.16666667, 0.        , 0.0952381 ],
       [1.        , 0.88095238, 0.95238095, 0.92857143]])

In [32]:
np.reshape(grades , shape=(1,20))

array([[ 85,  78,  92,  88,  70,  76,  80,  65,  90,  88,  94,  91,  60,
         65,  58,  62, 100,  95,  98,  97]])

second part - linear regression - 

In [33]:
x = np.array([50, 60, 80, 100, 120])
y = np.array ([150, 180, 240, 300, 330])

In [36]:
x = np.reshape(x, shape=(-1,1))
x

array([[ 50],
       [ 60],
       [ 80],
       [100],
       [120]])

In [37]:
ones = np.ones_like(x)
ones

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [38]:
x = np.hstack((x , ones ))
x

array([[ 50,   1],
       [ 60,   1],
       [ 80,   1],
       [100,   1],
       [120,   1]])

In [39]:
xtrans = np.matrix_transpose(x)
xtrans

array([[ 50,  60,  80, 100, 120],
       [  1,   1,   1,   1,   1]])

In [40]:
# first part of the equation :
temp = np.matmul(xtrans , x)
temp

array([[36900,   410],
       [  410,     5]])

In [41]:
# inverse of the previous part :
temp = np.linalg.inv(temp)
print(temp.shape)
temp

(2, 2)


array([[ 3.04878049e-04, -2.50000000e-02],
       [-2.50000000e-02,  2.25000000e+00]])

In [42]:
# second part of the equation :
temp2 = np.matmul(temp , xtrans)
print(temp2.shape)
temp2

(2, 5)


array([[-9.75609756e-03, -6.70731707e-03, -6.09756098e-04,
         5.48780488e-03,  1.15853659e-02],
       [ 1.00000000e+00,  7.50000000e-01,  2.50000000e-01,
        -2.50000000e-01, -7.50000000e-01]])

In [43]:
theta = temp2@y
theta

array([ 2.65243902, 22.5       ])

In [44]:
# the expectation :
house_size = np.array([90 , 1])
expectation = theta@house_size
expectation 

np.float64(261.21951219512243)